### ISSUE TITLE
Problemas para correr el ejemplo

### ISSUE THREAD

**Issue by Seba-san** [nicoRomeroCuruchet/BCRA_data#1]
Probe correr el archivo "BCRA.ipynb" desde google colab (para acceder al ejemplo hacer click [AQUI](https://colab.research.google.com/github/nicoRomeroCuruchet/BCRA_data/blob/main/BCRA.ipynb)) y en la celda 4, sale el siguiente mensaje de error:

         ` JSONDecodeError: [Errno Expecting value] Unauthorized Request: No Access Token`

Este error corresponde a la primer linea de codigo:
`df_eventos = api_bcra.get_milestones()`

pero si ejecutas cualquier otra con "get_** " pasa lo mismo.
Adjunto la imagen del error:
![Screenshot from 2023-04-11 14-27-44](https://user-images.githubusercontent.com/34282916/231243076-9aea07f2-badd-47a7-94bb-776fc918fb46.png)

**Comment by nicoRomeroCuruchet** [comment]
Seba para poder usarlo tenes que registrar tu email y generar un token en esta web:

https://estadisticasbcra.com/api/documentacion

Ahora cito en el readme a la web  que es la que está haciendo todo el laburo. Yo simplemente lo metí en una clase de python lo arregle un poco para que se vea bien, agregue datos de la reserva federal, ccl y mep. Quizas habria que poner los datos de ROFEX.

**Comment by Seba-san** [comment]
Genial! gracias!
